# Generated by Django 4.2.11 on 2026-06-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('tone', models.CharField(choices=[('viral', 'Viral Hook/Aggressive'), ('story', 'Deep Storytelling'), ('brainrot', 'Gen-Z / Brainrot'), ('educational', 'Informative/Educational')], default='viral', max_length=50)),
                ('raw_response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
