# Generated by Django 6.0.5 on 2026-06-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_scriptbatch_alter_joblisting_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_network', models.CharField(default='Global', max_length=100)),
                ('service_offered', models.CharField(max_length=255)),
                ('target_industry', models.CharField(max_length=255)),
                ('generated_pitch', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='company_website',
        ),
        migrations.AddField(
            model_name='scriptbatch',
            name='audio_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='apply_url',
            field=models.URLField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scriptbatch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
