# Generated by Django 6.0.5 on 2026-06-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_emailcampaign_remove_joblisting_company_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='salary_range',
            field=models.CharField(blank=True, default='$40,000 - $80,000', max_length=100, null=True),
        ),
    ]
