# Generated by Django 6.0.5 on 2026-06-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobcategory_joblisting_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-submitted_at'], 'verbose_name_plural': 'Job Applications'},
        ),
        migrations.AlterModelOptions(
            name='joblisting',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Job Listings'},
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about this applicant', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='benefits',
            field=models.TextField(blank=True, help_text='Extracted benefits and perks', null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='company_description',
            field=models.TextField(blank=True, help_text='Description of the company hiring', null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='employment_type',
            field=models.CharField(blank=True, help_text='Full-time, Part-time, Contract, etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='experience_level',
            field=models.CharField(blank=True, help_text='Entry level, Mid-level, Senior, etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='requirements',
            field=models.TextField(blank=True, help_text='Extracted requirements and qualifications', null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='responsibilities',
            field=models.TextField(blank=True, help_text='Extracted key responsibilities for this role', null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/%d/'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job', 'submitted_at'], name='jobs_jobapp_job_id_65a5ed_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['email'], name='jobs_jobapp_email_bb1ed9_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['is_reviewed'], name='jobs_jobapp_is_revi_689471_idx'),
        ),
        migrations.AddIndex(
            model_name='joblisting',
            index=models.Index(fields=['title'], name='jobs_joblis_title_da092b_idx'),
        ),
        migrations.AddIndex(
            model_name='joblisting',
            index=models.Index(fields=['company_name'], name='jobs_joblis_company_e94c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='joblisting',
            index=models.Index(fields=['category'], name='jobs_joblis_categor_5ac636_idx'),
        ),
        migrations.AddIndex(
            model_name='joblisting',
            index=models.Index(fields=['location'], name='jobs_joblis_locatio_6129f1_idx'),
        ),
        migrations.AddIndex(
            model_name='joblisting',
            index=models.Index(fields=['created_at'], name='jobs_joblis_created_7f6d8b_idx'),
        ),
    ]
