# Generated by Django 6.0.5 on 2026-07-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_joblisting_is_active_joblisting_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='views_count',
            field=models.IntegerField(default=0, help_text='Number of times this job has been viewed'),
        ),
    ]
