# Generated by Django 6.0.5 on 2026-07-09 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_jobapplication_views_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='views_count',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='slug',
            field=models.SlugField(blank=True, help_text='SEO-friendly URL slug generated from the title', max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='views_count',
            field=models.IntegerField(default=0, help_text='Number of times this job has been viewed'),
        ),
        migrations.AddIndex(
            model_name='joblisting',
            index=models.Index(fields=['slug'], name='jobs_joblis_slug_c255c3_idx'),
        ),
        migrations.AddIndex(
            model_name='joblisting',
            index=models.Index(fields=['is_active'], name='jobs_joblis_is_acti_861fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='joblisting',
            index=models.Index(fields=['is_featured'], name='jobs_joblis_is_feat_4a38e5_idx'),
        ),
    ]
