# Generated by Django 5.0.6 on 2026-07-26 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Professional'), ('enterprise', 'Enterprise')], default='starter', max_length=20)),
                ('paystack_subscription_code', models.CharField(blank=True, help_text='Paystack subscription code (e.g., SUB_xxxxx)', max_length=100, null=True)),
                ('paystack_customer_code', models.CharField(blank=True, help_text='Paystack customer code (e.g., CUS_xxxxx)', max_length=100, null=True)),
                ('job_posts_remaining', models.IntegerField(default=5, help_text='Number of job posts remaining this month. -1 = unlimited (Enterprise)')),
                ('is_active', models.BooleanField(default=False, help_text='Whether the subscription is currently active')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this subscription expires (if not renewed)', null=True)),
                ('next_billing_date', models.DateTimeField(blank=True, help_text='When the next payment is due', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='dashboard_s_user_id_61499d_idx'), models.Index(fields=['paystack_subscription_code'], name='dashboard_s_paystac_40875b_idx'), models.Index(fields=['plan_type'], name='dashboard_s_plan_ty_6bc700_idx')],
            },
        ),
    ]
